name: Run Autonoma Tests

on:
  deployment_status:
jobs:
  run-folder-cm8olka7u000qf9fg3fe4fh3v:
    runs-on: ubuntu-latest
    name: Autonoma Test "Autonoma Bank"
 
    steps:
      - name: Run Folder Tests "Autonoma Bank"
        id: step-1
        uses: autonoma-ai/actions/folder-runner@v1
        with:
          folder-id: 'cm8olka7u000qf9fg3fe4fh3v'
          client-id: ${{ secrets.AUTONOMA_CLIENT_ID }}
          client-secret: ${{ secrets.AUTONOMA_CLIENT_SECRET }}
          max-wait-time: '10' #IN MINUTES
      - name: Show "Autonoma Bank" results
        if: always()
        run: |
          echo "Test status: ${{ steps.step-1.outputs.final-status }}"
          echo "Message: ${{ steps.step-1.outputs.message }}"
          echo "View results at: ${{ steps.step-1.outputs.url }}"
