name: Run Autonoma Tests

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Uses GitHub's Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repo

      - name: Run Tests on Autonoma API
        run: |
          curl -X POST \
            --silent \
            --retry 3 \
            --retry-connrefused \
            --location 'https://api.prod.autonoma.app/v1/run/folder/cm8olka7u000qf9fg3fe4fh3v' \
            --header "autonoma-client-id: ${{ secrets.AUTONOMA_CLIENT_ID }}" \
            --header "autonoma-client-secret: ${{ secrets.AUTONOMA_CLIENT_SECRET }}" \
            --header 'Content-Type: application/json'
